### ISSUE TITLE
PyPI sdist error

### ISSUE THREAD

**Issue by jayvdb** [futursolo/magichttp#5]
```py
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    i for i in open("setup-requirements.txt").read().split("\n") if i]
FileNotFoundError: [Errno 2] No such file or directory: 'setup-requirements.txt'
```

**Comment by futursolo** [comment]
Fixed in https://github.com/futursolo/magichttp/commit/7d627793a4f2fec440edde04aaca5f19e8d4e6d1.

I still have some other changes that I wish to include in the next release.

I will arrange a release as soon as possible.

**Comment by jayvdb** [comment]
No worries, and no rush; I'll do openSUSE distro packaging when you get the release out, so a note here on release would be helpful.

**Comment by futursolo** [comment]
The latest release(`v1.1.0`) has been published to PyPI.

Since you are packaging this repo for a Linux distribution, I would suggest you watch this repo(Release Only) in order to receive notifications for updates in the future.

Please let me know if you encounter any other issues with packaging. :)
